"""empty message

Revision ID: 5cfdfd657f2e
Revises: 55eb8d832b56
Create Date: 2019-10-29 21:14:15.342213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cfdfd657f2e'
down_revision = '55eb8d832b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.Text(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'artist_genre', ['genre_id', 'artist_id'])
    op.create_unique_constraint(None, 'venue_genre', ['genre_id', 'venue_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue_genre', type_='unique')
    op.drop_constraint(None, 'artist_genre', type_='unique')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
